name = "Медицинские изделия и расходные материалы"
keywords = ["медицинск* издели*", "расходн* материал* медицинск*", "шприц*", "катетер*", "перчатк* медицинск*", "перчатк* хирургическ*", "перевязочн*"]
minus = ["ремонт*", "обслуживан*", "поверк*", "метрологи*"]
okpd2 = ["32.50"]
