name = "Хозтовары и бытовая химия"
keywords = ["хозяйственн* товар*", "бытов* хими*", "моющ* средств*", "чистящ* средств*", "мешк* для мусора", '"бумага туалетная"']
minus = ["услуг*"]
okpd2 = ["20.41", "17.22"]
