name = "Строительные материалы"
keywords = ["строительн* материал*", "стройматериал*", "цемент*", "кирпич*", "пиломатериал*", "лакокрасочн*"]
minus = ["ремонт*"]
okpd2 = ["23.51", "23.32", "16.10", "20.30"]
